// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_zjcOWBNyEVK8Gx_sgQ76R7-HU9buX7A',
    appId: '1:951139021852:web:74e58a287ec4ce14639bd9',
    messagingSenderId: '951139021852',
    projectId: 'sign-login-79a16',
    authDomain: 'sign-login-79a16.firebaseapp.com',
    databaseURL: 'https://sign-login-79a16-default-rtdb.firebaseio.com',
    storageBucket: 'sign-login-79a16.appspot.com',
    measurementId: 'G-1GKJ6YF6YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiu1iBbabqysw7hTZoLCYt9_9KO-Tkb0I',
    appId: '1:951139021852:android:7665ee993a757945639bd9',
    messagingSenderId: '951139021852',
    projectId: 'sign-login-79a16',
    databaseURL: 'https://sign-login-79a16-default-rtdb.firebaseio.com',
    storageBucket: 'sign-login-79a16.appspot.com',
  );
}
